### ISSUE TITLE
UX Kugghjul för utloggning

### ISSUE THREAD

**Issue by dnov-swe** [kolplattformen/skolplattformen#316]
When logged in there is a cog wheel icon which signals "settings", though the only option presented in pop up menu is to log out.

Switch to an icon that signals log out.

**Comment by axdra** [comment]
Either this, or just add a settings screen after login, some settings should maybe just be accessible after login.

**Comment by zhouhana** [comment]
though.

Regarding a settings screen after login, it would need to be shown only after the first login, otherwise it would become annoying. And then you’d need a way anyway to change those settings later. Regarding language switching for example, I assume that the app follows the language hierarchy in the device settings, so most users should simply be okay with the language selected for them. Sometimes you might want the ability to switch back and forth in-app, though: if your default language isn’t translated completely or even correctly (common in open source), or if you’re a translator testing out strings in context, or if you’re doing your best to use the app in Swedish but just need a quick Somali translation of “Matsedel”. 🙂

**Comment by zhouhana** [comment]
I vote to keep the menu, even though *right now* there is only one item in it. But perhaps the symbol should instead be a “hamburger”, three little dots, or some other, universal and more general More/Menu symbol.

I can imagine at least five options that would fit well in this menu right now:

Om Öppna Skolplattformen
Stöd oss på Patreon!
Rapportera ett problem
Byt språk
Logga ut

Only one of the above is a setting, though.

Regarding a settings screen after login, it would need to be shown only after the first login, otherwise it would become annoying. And then you’d need a way anyway to change those settings later. Regarding language switching for example, I assume that the app follows the language hierarchy in the device settings, so most users should simply be okay with the language selected for them. Sometimes you might want the ability to switch back and forth in-app, though: if your default language isn’t translated completely or even correctly (common in open source), or if you’re a translator testing out strings in context, or if you’re doing your best to use the app in Swedish but just need a quick Somali translation of “Matsedel”. 🙂

**Comment by comradekingu** [comment]
Om
→ Rapporter problem
→ Patreon
Logg ut

With only two things to pick from, and "Om" encompassing both rapporting problems and various donation platforms, there is no need to click a menu and then click something else in it.

Lets translate it the right way https://hosted.weblate.org/projects/skolplattformen/
and not bog down the menu with stopgap options in its absence.
