### ISSUE TITLE
Have to launch twice on Android

### ISSUE THREAD

**Issue by walles** [kolplattformen/skolplattformen#639]
I'm on Android.

Every time I launch the app for the first time any day, *something* happens but the app never starts.

Second attempt, it starts as expected.

This has been the case for as long as I have been using it. Half a year perhaps?

I have never seen any other app have this problem.

Closing the app and then starting it again does not reproduce the problem.

Waiting for the next day and starting the app always reproduces the problem for me.

**Comment by kajetan-kazimierczak** [comment]
I just tried to start the app on an Android device that I haven't used for weeks and it started without problems on the first try.
I have version 3.0.5 (20426) running, witch I suppose is a beta, but not much has changed since the last stable, beside som new translations.

What device do you use? What version of Android? What version of the app (can be found in settings)? We'll se if we can find something.

**Comment by walles** [comment]
Just started this combo after maybe two weeks since last time (Christmas break, woho!), and now it worked on the first attempt.

I'll just close this for now, and if it starts happening again I'll reopen.

For completeness, here are the answers to your questions:
* Samsung Galaxy S21 5G, SM-G991B/DS
* Android 13
* Version 3.0.4 (20424)
